openapi: "3.0.0"

info:
  description: "HTTP endpoints docs"
  version: "1.0"
  title: "Savings Planner API"

paths:
  "/api/auth/users":
    post:
      summary: "Create a new user account"
      requestBody:
        description: "User data"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/RegistrationRequest"
      responses:
        "200":
          description: "User has been created"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
        "400":
          description: "Invalid request body"
        "409":
          description: "Email or nick already taken"

  "/api/auth/access-token":
    post:
      summary: "Get new access token"
      requestBody:
        description: "User credentials"
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: "User has been created"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
        "400":
          description: "Invalid request body"
        "401":
          description: "Wrong login or password"

components:
  schemas:
    RegistrationRequest:
      type: "object"
      properties:
        nick:
          type: "string"
          pattern: ^\w{3,16}$
        email:
          type: "string"
          format: "email"
        password:
          type: "string"
          format: "password"
          minLength: 7
          maxLength: 100

    LoginRequest:
      type: "object"
      properties:
        login:
          type: "string"
          format: "nick or email"
        password:
          type: "string"
          format: "password"
          minLength: 7
          maxLength: 100

    AccessTokenResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
