openapi: "3.0.3"

info:
  title: "Savings Planner API"
  description: "HTTP endpoints docs"
  version: "1.0"

paths:
  "/api/auth/users":
    post:
      summary: "Creates new user account"
      requestBody:
        description: "User data"
        required: true
        content:
          "application/json":
            schema:
              "$ref": "#/components/schemas/RegistrationRequest"
      responses:
        "200":
          description: "User has been created"
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/AccessTokenResponse"
        "400":
          description: "Invalid request body"
        "409":
          description: "Email or nick already taken"

  "/api/auth/access-token":
    post:
      summary: "Gets new access token"
      requestBody:
        description: "User credentials"
        required: true
        content:
          "application/json":
            schema:
              "$ref": "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: "Login successful"
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/AccessTokenResponse"
        "400":
          description: "Invalid request body"
        "401":
          description: "Wrong login or password"

components:
  schemas:
    RegistrationRequest:
      type: "object"
      properties:
        nick:
          type: "string"
          pattern: ^\w{3,16}$
        email:
          type: "string"
          format: "email"
        password:
          type: "string"
          format: "password"
          minLength: 7
          maxLength: 100

    LoginRequest:
      type: "object"
      properties:
        login:
          type: "string"
          format: "nick or email"
        password:
          type: "string"
          format: "password"
          minLength: 7
          maxLength: 100

    AccessTokenResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
          format: "encoded access token"
          example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImV4cCI6MTY0OTk2MTYzOCwidXNlcklkIjoxfQ.rWcKHXk8Q-QWchLEEBRlxSS3owbbQa5azSM4ag5ogpY"

    AccessToken:
      type: "object"
      description: "Decoded token structure"
      properties:
        header:
          type: "object"
          properties:
            alg:
              type: "string"
              default: "HS256"
            typ:
              type: "string"
              default: "JWT"
        payload:
          type: "object"
          properties:
            sub:
              type: "string"
              format: "nick"
              description: "Owner of the token"
            exp:
              type: "integer"
              format: "int64"
              description: "Expiration (Unix epoch second)"
            userId:
              type: "integer"
              format: "int32"
              description: "Owner's ID"
